from datetime import timedelta

WIDTH = 640
MIN_START_BALANCE = 1
MAX_START_BALANCE = 1_000_000
DEFAULT_START_BALANCE = 10_000
DEFAULT_OPTIONS = ['Yandex clA', 'Сбербанк', 'МТС-ао', 'ВТБ ао']
MAX_PORTFOLIO_SIZE = 10
DATA_INTERVAL = timedelta(days=365 * 10)
DEFAULT_DATE_INTERVAL = timedelta(days=90)
DEFAULT_RISK_FREE_RATE = 7.5
DEFAULT_RISK_TARGET = 20.0
DEFAULT_RETURNS_TARGET = 20.0
